---
version: "3.7"

services:
  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_USER=test
      - KEYCLOAK_PASSWORD=password
    volumes:
      - ./tmp:/tmp
